### PR TITLE
Added Get-UnityHostInitiator function.

### PR DESCRIPTION
**Pull request by BrandonStiff**
Hi there.  Your Unity-PoweShell module has come in very handy.  I added  a new function that I noticed was missing.  I believe I've followed the proper procedure for having my changes merged into your master module.  Please let me know if any further changes need to be made to render it acceptable.  This is my first time requesting a Pull in GitHub so pardon any noob-ish mistakes or oversights.  Thanks!

### CODE REVIEW

**Comment by equelin** [comment]
:white_check_mark: [Build Unity-Powershell 1.0.54 completed](https://ci.appveyor.com/project/equelin/unity-powershell/build/1.0.54) (commit https://github.com/equelin/Unity-Powershell/commit/3a84ebbf0d by @BrandonStiff)

**Comment by equelin** [comment]
Hello @BrandonStiff 

First of all thank you very much for your pull request, I appreciate it! 
I'll look to your code this weekend and come back to you asap. I think you've done a good job by modifying every needed files.

Would you mind to [change your PR](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) to commit into the develop branch ? I'm using the master branch when I want to release a new version of the module.

Thanks.

**Comment by equelin** [comment]
You're code is OK, I'll accept the PR when you'll have changed the branch.

Thanks again !

**Comment by BrandonStiff** [comment]
Will do, thanks!

________________________________

**Comment by BrandonStiff** [comment]
OK, I believe I've changed the target branch to "develop" correctly.

**Comment by equelin** [comment]
I've merged your PR. Thank you @BrandonStiff for your work on the module !

**Pull request merged**
