### PR TITLE
Added feature to update PS window titlebar with connected-Unity-session info

### PR DESCRIPTION
**Pull request by mtboren**
..as part of enhancement request in #19.  At each `Connect-Unity` and `Disconnect-Unity` invocation, PowerShell window titlebar will be updated with information about the Unity array(s) to which current session is connected, if any.

Useful, especially when managing multiple Unity storage arrays.

### CODE REVIEW

**Comment by equelin** [comment]
:white_check_mark: [Build Unity-Powershell 1.0.66 completed](https://ci.appveyor.com/project/equelin/unity-powershell/build/1.0.66) (commit https://github.com/equelin/Unity-Powershell/commit/e2aaccfb11 by @mtboren)

**Comment by equelin** [comment]
Thank you for the PR!

Would you mind to change the destination branch to `develop` ? I'm only using `master` to automatically release new version of the module (new github release and new version in Powershellgallery).

Unfortunatly I've made a lot of changed in `develop` so you might have to correct some conflicts before being able to merge. Also please note that the version of the module is `0.13.0` in the `develop` branch so you no longer need to change it in your PR.

Ping me if you have some trouble with this PR!

**Comment by equelin** [comment]
:white_check_mark: [Build Unity-Powershell 1.0.71 completed](https://ci.appveyor.com/project/equelin/unity-powershell/build/1.0.71) (commit https://github.com/equelin/Unity-Powershell/commit/15914933f3 by @mtboren)

**Comment by mtboren** [comment]
Greets-

Sure thing!  As for changing the destination to an appropriate branch -- I probably should have checked on that to start with.  My bad.  As for the actual act of changing the target branch:  I've not done that before, but from what I could tell, GHub provides that ability to just change the target branch right in the Pull Request itself.  So, I did.  It seems like things are good (had to resolve one conflict), but -- seem good to you, too?

**Pull request merged**
